##                       ##
##  Test on current LTS  ##
##                       ##

FROM node:4.5

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY . /usr/src/app

# Make sure the container keeps running
CMD [ "/bin/cat" ]
