##                   ##
##  Test on old LTS  ##
##                   ##

FROM node:0.10

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# install promise library for any-promise
RUN npm install bluebird

# Bundle app source
COPY . /usr/src/app

# Make sure the container keeps running
CMD [ "/bin/cat" ]
